# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	mesa-libs
PORTVERSION=	${MESAVERSION}
CATEGORIES=	graphics

COMMENT=	OpenGL libraries that support GLX and EGL clients

LIB_DEPENDS=	libGL.so:graphics/mesa

.include "${.CURDIR:H:H}/graphics/mesa/Makefile.common"

.include <bsd.port.post.mk>
