# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	mesa-dri
PORTVERSION=	${MESAVERSION}
CATEGORIES=	graphics

COMMENT=	OpenGL hardware acceleration drivers for DRI2+

LIB_DEPENDS=	libGL.so:graphics/mesa

.include "${.CURDIR:H:H}/graphics/mesa/Makefile.common"

.include <bsd.port.post.mk>
